export const createEngineUiRefs = () => ({
    resumeBtn: document.getElementById('resume-btn'),
    bgmSlider: document.getElementById('bgm-volume'),
    sfxSlider: document.getElementById('sfx-volume'),
    shareBtn: document.getElementById('share-btn'),
    returnHomeBtn: document.getElementById('return-home-btn'),
    tutorialBtn: document.getElementById('tutorial-btn'),
    startBtn: document.getElementById('start-btn'),
    tutorialOverlay: document.getElementById('tutorial-overlay'),
    tutorialTitle: document.getElementById('tutorial-title'),
    tutorialSubtitle: document.getElementById('tutorial-subtitle'),
    tutorialBody: document.getElementById('tutorial-body'),
    tutorialPrevBtn: document.getElementById('tutorial-prev-btn'),
    tutorialNextBtn: document.getElementById('tutorial-next-btn'),
    tutorialCloseBtn: document.getElementById('tutorial-close-btn'),
    reviveBtn: document.getElementById('revive-btn'),
    reviveContainer: document.getElementById('revive-container'),
    reviveTimer: document.getElementById('revive-timer'),
    escapeMenu: document.getElementById('escape-menu'),
    deathScreen: document.getElementById('death-screen'),
    levelUpScreen: document.getElementById('level-up-screen'),
    upgradeList: document.getElementById('upgrade-list'),
    timer: document.getElementById('timer'),
    finalTime: document.getElementById('final-time')
});
